module.exports = [
  "",
  {
    title: "快速上手",
    collapsable: false,
    prefix: "guide/",
    children: [
      "",
      "selector",
      "declaration",
      "import",
      "cascade",
      "box",
      "common",
    ],
  },
  {
    title: "CSS 介绍",
    collapsable: false,
    prefix: "intro/",
    children: [
      "selector",
      "box",
      "background-and-border",
      "font",
      "text-direction",
      "overflow",
      "value",
      "sizing",
      "replaced",
      "media",
    ],
  },
  {
    title: "CSS 布局",
    collapsable: false,
    prefix: "layout/",
    children: ["intro", "flow", "float", "flex", "exercise", "grid"],
  },
];
