module.exports = [
  "",
  {
    title: "TS 介绍",
    path: "intro/",
    collapsable: false,
    prefix: "intro/",
    children: ["what-is-typescript", "get-typescript", "hello-typescript"],
  },
  {
    title: "TS 基础教程",
    path: "basics/",
    collapsable: false,
    prefix: "basics/",
    children: [
      "primitive-data-types",
      "any",
      "type-inference",
      "union-types",
      "type-of-object-interfaces",
      "type-of-array",
      "type-assertion",
      "declaration-files",
      "built-in-objects",
    ],
  },
  {
    title: "TS 进阶教程",
    prefix: "advanced/",
    children: [
      "",
      "type-aliases",
      "string-literal-types",
      "tuple",
      "enum",
      "class",
      "class-and-interfaces",
      "generics",
      "declaration-merging",
      "further-reading",
    ],
  },
  {
    title: "TS 工程",
    prefix: "engineering/",
    children: ["", "lint"],
  },
];
