module.exports = [
  "",
  "file-structure",
  "env",
  {
    title: "配置",
    collapsable: false,
    prefix: "config/",
    children: ["", "app-config", "page-config", "sitemap-config"],
  },
  {
    title: "框架",
    collapsable: false,
    prefix: "frame/",
    children: ["intro", "scene", "env", "mechanism", "update"],
  },
  {
    title: "逻辑层",
    collapsable: false,
    prefix: "service/",
    children: [
      "",
      "lifetime",
      "route",
      "register",
      "app",
      "page",
      "run",
      "module",
      {
        title: "API",
        prefix: "api/",
        children: ["", "route", "storage", "interact", "network", "system"],
      },
    ],
  },
  {
    title: "视图层",
    collapsable: false,
    prefix: "view/",
    children: [
      "",
      {
        title: "WXML",
        icon: "code",
        children: [
          "wxml",
          "data-bind",
          "condition-render",
          "list-render",
          "template",
        ],
      },
      "wxss",
      "event",
      "component",
      "animation",
      "wxs",
      "wxs-event",
      "model",
      "selector",
      "rendering-cache",
    ],
  },
  {
    title: "能力",
    collapsable: false,
    prefix: "ability/",
    children: ["", "network", "storage", "file-system", "debug"],
  },
];
